/*
 * API для взаимодействия с STM32MP1
 *
 * Данное API чото гдето зочемто нужно, не очень понятно. Но пусть будет, что мешает штоли?
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"FileAddElem",
		strings.ToUpper("Post"),
		"/file/elem/add",
		FileAddElem,
	},

	Route{
		"FileRemoveElem",
		strings.ToUpper("Post"),
		"/file/elem/remove",
		FileRemoveElem,
	},

	Route{
		"GetFilePhones",
		strings.ToUpper("Get"),
		"/file/get",
		GetFilePhones,
	},

	Route{
		"SetFilePhones",
		strings.ToUpper("Post"),
		"/file/set",
		SetFilePhones,
	},

	Route{
		"GetSmsMessage",
		strings.ToUpper("Get"),
		"/sms/read",
		GetSmsMessage,
	},

	Route{
		"GetSmsModemSt",
		strings.ToUpper("Get"),
		"/sms/modem/info",
		GetSmsModemSt,
	},

	Route{
		"SetSendSms",
		strings.ToUpper("Post"),
		"/sms/send",
		SetSendSms,
	},
}
